// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// rcppeigen_max_over_columns_or_rows
Eigen::MatrixXd rcppeigen_max_over_columns_or_rows(const Eigen::Map<Eigen::MatrixXd>& A, int& dimen);
RcppExport SEXP ISOpureR_rcppeigen_max_over_columns_or_rows(SEXP ASEXP, SEXP dimenSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP );
        Rcpp::traits::input_parameter< int& >::type dimen(dimenSEXP );
        Eigen::MatrixXd __result = rcppeigen_max_over_columns_or_rows(A, dimen);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
